image: piposaude/build-pipo-clj:1.1

fmt-check:
  script:
    - bin/fmt-check
  rules:
    - if: $CI_MERGE_REQUEST_IID

unit-tests:
  script:
    - bin/eftest
  rules:
    - if: $CI_MERGE_REQUEST_IID
