name: build-and-test

on:
  pull_request:
      branches:
        - main
      paths-ignore:
        - 'showcase/**'
        - 'doc/**'
  workflow_dispatch:

jobs:
  format-check:
    name: 'Format Check'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make fmt-check

  lint:
    name: 'Lint'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make lint

  unit-test:
    name: 'Unit Tests'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make test

  test-cljs:
    name: 'Unit Tests for cljs'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make test-cljs
