name: build-and-test

on:
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  format-check:
    name: 'Format Check'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make fmt-check

  unit-test:
    name: 'Unit Tests'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make test
