name: performance-test-quick

on:
  workflow_dispatch:

jobs:
  performance-test-quick:
    name: 'Quick performance test'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: QUICK_PERF_TESTS=true make perftest
