name: performance-teste

on:
  workflow_dispatch:

jobs:
  performance-test:
    name: 'Performance test'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make perftest

  quick-performance-test:
    name: 'Quick performance test'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: QUICK_PERF_TESTS=true make perftest
