name: pull-request-checks
on:
  pull_request:
      branches:
        - main
  workflow_dispatch:


jobs:
  format-check:
    name: Setup and run
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: ./bin/fmt-check

  unit-test:
    name: Setup and run
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: ./bin/eftest
