name: release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: '11'
          server-id: clojars
          server-username: MAVEN_USERNAME
          server-password: MAVEN_TOKEN

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: 1.11.1.1155
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clj and cljs tests against generated jar
        run: make test-all-libs

      - name: Run performance tests
        run: make perftest

      - name: Release
        run: make release
        shell: bash
        env:
          MAVEN_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          MAVEN_TOKEN:    ${{ secrets.CLOJARS_TOKEN }}
