name: release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: 'Release'
    uses: ./.github/workflows/setup-and-run-script.yml
    with:
      script: make release
      username: ${{ secrets.CLOJARS_USERNAME }}
      token: ${{ secrets.CLOJARS_TOKEN }}
